[package]
name = "restate-timer"
version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish = false

[features]
default = []
options_schema = ["dep:schemars"]

[dependencies]
restate-types = { workspace = true }

ahash = "0.8.3"
derive_builder = { workspace = true }
futures = { workspace = true }
pin-project = { workspace = true }
priority-queue = "1.3.1"
schemars = { workspace = true, optional = true }
serde = { workspace = true }
serde_with = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true }
tokio-stream = { workspace = true }
tokio-util = { workspace = true }
tracing = { workspace = true }

[dev-dependencies]
restate-test-util = { workspace = true }

futures-util = { workspace = true }
tracing-subscriber = { workspace = true }
test-log = { workspace = true }

